### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by stanoddly** [TheSpydog/SDL_gpu_examples#45]
I've just noticed that the repository doesn't have any license, so this implies all rights are reserved... :sweat_smile: Could the license be clarified and added?

[Here](https://opensource.stackexchange.com/a/1721)'s more info about the problem.

**Comment by TheSpydog** [comment]
Ah, right... this repo started as basically just a test suite for the GPU team so I forgot to ever add a license.

@ritalat @Akaricchi Since you've contributed to the repo, is it cool with you if I add the zlib license?

**Comment by Akaricchi** [comment]
Sure

**Comment by ritalat** [comment]
Fine by me.

**Comment by TheSpydog** [comment]
Thanks all! License has been added in https://github.com/TheSpydog/SDL_gpu_examples/commit/9c6637414df06fa1479e2c9a696254382526f72b.
