### ISSUE TITLE
Post effect shader

### ISSUE THREAD

**Issue by amirrajan** [TheSpydog/SDL_gpu_examples#48]
I’m trying to reason through how these APIs could be used to apply post effects to something that is primarily rendered using sdl’s 2D api. Basically a final pass to a rendered/backbuffer before presenting to the screen.

Any pointers?

**Comment by amirrajan** [comment]
As an example: I want to see what a game would look like to someone that has protanopia (color blind). Being able to pass the final scene to a shader to perform that processing would be freaking awesome

**Comment by thatcosmonaut** [comment]
The Tonemapping example is a good example of how to do a post-process effect. 

There are currently no plans for interop between the Render and GPU APIs. If you need shader effects you should use the GPU API.
